# Generated by Django 4.0.2 on 2022-02-11 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='page_character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('race', models.CharField(max_length=30)),
                ('capabilities_character', models.CharField(max_length=250)),
                ('age_character', models.IntegerField()),
                ('children_character', models.CharField(max_length=50)),
                ('parents_character', models.CharField(max_length=50)),
                ('artifacts_character', models.CharField(max_length=100)),
                ('date_add_character', models.DateTimeField(verbose_name=datetime.datetime(2022, 2, 11, 17, 28, 37, 210459))),
            ],
        ),
    ]
