# Generated by Django 4.0.2 on 2022-02-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_page_character_age_character_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page_character',
            name='type_objects',
            field=models.CharField(blank=True, choices=[('Персонаж', 'Персонаж'), ('Артефакт', 'Артефакт'), ('География', 'География')], max_length=50),
        ),
    ]
