# Generated by Django 4.0.2 on 2022-03-02 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_page_character_type_objects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_objects', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='page_character',
            name='type_objects',
        ),
        migrations.AddField(
            model_name='page_character',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='articles.category'),
        ),
    ]
